grammar YARMO (ЯРМО) 


адрес ::= переменная | адресная-пара | косвенность .

адресная-пара ::= "/" [константа ","] константа "/" .

константа ::= константа-простая | константное-выражение .

константа-простая ::= операнд-константного-выражения .

операнд-константного-выражения ::= изображения-значения | имя | аттрибут | составное .

константное-выражение ::= операнд-константного-выражения { операция операнд-константного-выражения } .

аттрибут ::= ("ир" | "смещ" ) имя
	     | ("ирдан" | "смещдан") имя
	     | "размер" имя
	     | ("размлок" | "размпар" | "чиспар") имя¤процедуры¤
	     | "номерсег" имя¤процедуры¤
	     | ("прагр" | "левгр") имя¤записи¤ .

блок ::= "начало" описание "вход" предложение "конец" .

косвенность ::= первичное "^" [ адресная-пара | имя_переменной | имя_записи ["." селектор_записи]] .

изображение-значения ::= число | набор | составное | строка .

число ::= целое | рациональное .
целое ::= положительное | отрицательное .
положительное ::= цифра {цифра} .
отрицательное ::= "-" положительное .

двоичная_цифра ::= "0" | "1" .
восьмеричная_цифра ::= двоичная_цифра | "2" | "3" | "4" | "5" | "6" | "7" .
цифра ::= восьмеричная_цифра | "8" | "9" .
шестнадцатеричная_цифра ::= цифра | "A" | "B" | "C" | "D" | "E" | "F" .

рациональное ::= целое "." положительное [ "E" целое ] .

набор ::= шестнадцатеричный | восьмеричный | двоичный | текстовый .

шестнадцатеричный ::= шестнадцатеричный_префикс шестнадцатеричная_цифра {шестнадцатеричная_цифра} .
шестнадцатеричный_префикс ::= "ш" | "шл" .

восьмеричный ::= восмиричный_префикс восьмеричная_цифра {восьмеричная_цифра} .
восмиричный_префикс ::= "в" | "вл" .

двоичный ::= двоичный_префикс двоичная_цифра {двоичная_цифра} .
двоичный_префикс ::= "д" | "дл" .

текстовый ::= ( "т" | "тл" ) '"' {литера} '"' .
строка ::= '"' {литера} '"' .

составное  ::= запись_для_составного "[" изображение-значения {"," изображение-значения} "]" . 
запись_для_составного ::= группа_параллельных_полей .
группа_параллельных_полей ::= "[" поле {"," поле} "]" .
поле ::= слог .
слог ::= граница ":" граница .
граница ::= положительное .

описание-записей ::= "записи" описание-записи {";" описание-записи} . 
описание-записи ::= имя "=" запись .
запись ::= имя | изображение-записи .

имя ::= буква { буква | цифра | "_" } .

изображение-записи ::= "/" размер-записи "/" 
		| "/" множитель "/" "х" компонента-массива 
		| группа-параллельных-полей 
		| группа-последовательных-полей .

изображение-значение ::= число 
						| набор 
						| составное 
						| строка
						| "истина" | "ложь" .

команда ::= "|>" {восьмеричная_цифра} "<|" . 
						 
компонента-массива ::= запись .

группа-параллельных-полей ::= "[" поле {"," поле} "]" .
группа-последовательных-полей ::= "(" поле {"," поле} ")" . 

поле ::= имя [ "=" ( запись| слог ) ] 
		| изображение-записи 
		| слог .
		 
размер-записи ::= константа .
множитель ::=константа .
граница ::= константа .

константа ::= простая-константа | постоянное-выражение .

косвенная ::= первичное "^" ( адресная-пара | имя  ) .

селектор-записи ::= ( изображение-значения | имя )["." селектор-записи ] .

описание констант ::= "константы" описание-константы {";" описание-константы } .
описание-константы ::= имя [":" запись ] "=" константа {"," константа2 } . 
описание-переменных ::= "переменные" описание-переменной {";" описание-переменной } .
описание-переменной ::= имя [ ":" запись ] .

переменная ::= имя ["." селектор-записи] .

формула ::= первичное [ операция первичное 
						| выделение-слога 
						| изменение-слога 
						| изменение-слога-с-засылкой 
						| засылка ] .
			
первичное ::= константа | адрес | "(" предложение ")" .

операция ::= операция-алгебраическая | операция-сравнения | операция-порязрядная .
операция-алгебраическая ::= "+" | "-" | "*" | "дел" | "умн" | "сл" | "вч" | "делр" .
операция-сравнения ::= "<" | "≤" | ">" | "≥" | "м" | "мр" | "б" | "бр" | "=" | "≠" .
операция-порязрядная ::= "∧" | "∨".

выделение-слога ::= "*" запись .
изменение-слога ::= "=>"  запись "*" первичное .
изменение-слога-с-засылкой ::= "->" запись "*" адрес .

засылка ::= простая-засылка | совмещенная-засылка .
простая-засылка ::= "->" адрес .
совмещенная-засылка ::= операция "->" адрес
		    	| "*" ("->" запись "*" адрес | "=>" запись "*" первичное )
			| операция "->" запись "*" адрес .

управление-первичное ::= альтернативное | циклическое .
альтернативное ::= условное | выбирающее | перебирающее .
условное ::= "если" условие "то" предложение ["иначе" предложение] "все" .
выбирающее ::= "выбор" предложение "из" предложение {"," предложение} ["иначе" предложение] "все" .
перебирающее ::= "перебор" предложение "из" (предложение {"," предложение} "то" предложение {"," предложение}) ["иначе" предложение] "все" .
условие ::= предложение [ "ист" | "неист" ] .

циклическое ::= 
    "пока" условие "цикл" предложение ["иначе" предложение] "все" | 
    "повторять" предложение ["когда" условие ["иначе" предложение]] "все" .

предложение ::= простое-предложение { ";" простое-предложение } .
простое-предложение ::= [имя¤метки¤ ":"] формула [завершитель] .
завершитель ::= "завершить" имя_уровня ["при" условие "все"] | "возврат" ["при" условие "все"] .

первичное ::= константа-простая
	      | адрес
	      | ":" имя_уровня ":" (альтернативное | циклическое | "(" предложение ")" | блок )
	      | вызов-модуля
	      | вызов-процедуры
	      | вызов-текста
	      | вызов-квазипроцедуры
	      | "адрес" (имя¤переменной-или-процедуры¤ ["." селектор-записи] | имя¤метки,процедуры,модуля,квази-процедуры¤  | "параметр" константа )
	      | имя¤формального-параметра¤
	      | "тело" повторитель .

